import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const jsonPath = path.join(__dirname, '../src/data/articles_complete.json')
const articles = JSON.parse(fs.readFileSync(jsonPath, 'utf8'))

// Clean imageUrl in json
const cleaned = articles.map((a) => ({
  ...a,
  imageUrl: ''
}))
fs.writeFileSync(jsonPath, JSON.stringify(cleaned, null, 2), 'utf8')

// Build allArticles.js
const imageImports = `import birthdayImg from '../assets/images/birthday-courtyard.jpg'
import grouphomeResidentsImg from '../assets/images/grouphome-residents.jpg'
import nationalTrustImg from '../assets/images/national-trust-event.jpg'

import buildingBlocksSvg from '../assets/images/mocks/building-blocks.svg'
import thinkingBoxSvg from '../assets/images/mocks/thinking-box.svg'
import visaAbroadSvg from '../assets/images/mocks/visa-abroad.svg'
import chanceEncounterSvg from '../assets/images/mocks/chance-encounter.svg'
import saiBabaSvg from '../assets/images/mocks/sai-baba.svg'
import speechTherapySvg from '../assets/images/mocks/speech-therapy.svg'
import artStudioSvg from '../assets/images/mocks/art-studio.svg'
import kadiamSvg from '../assets/images/mocks/kadiam.svg'
import physiotherapySvg from '../assets/images/mocks/physiotherapy.svg'
import dairySvg from '../assets/images/mocks/dairy.svg'
import gardeningSvg from '../assets/images/mocks/gardening.svg'
import guardianAngelSvg from '../assets/images/mocks/guardian-angel.svg'
import championsSvg from '../assets/images/mocks/champions.svg'
import recipeSuccessSvg from '../assets/images/mocks/recipe-success.svg'
import niosEducationSvg from '../assets/images/mocks/nios-education.svg'
import paperBagSvg from '../assets/images/mocks/paper-bag.svg'
import tailoringSvg from '../assets/images/mocks/tailoring.svg'
import kitchenSvg from '../assets/images/mocks/kitchen.svg'

export const articleImagesMap = {
  'home-of-care': birthdayImg,
  'group-homes': grouphomeResidentsImg,
  'bed-hotspot': nationalTrustImg,
  'building-blocks': buildingBlocksSvg,
  'story-thinking': thinkingBoxSvg,
  'story-visa': visaAbroadSvg,
  'story-encounter': chanceEncounterSvg,
  'story-direct-speak': chanceEncounterSvg,
  'story-sai-baba': saiBabaSvg,
  'story-15-years': speechTherapySvg,
  'story-art-equaliser': artStudioSvg,
  'story-kadiam': kadiamSvg,
  'story-exercise': physiotherapySvg,
  'story-covid': dairySvg,
  'story-dairy': dairySvg,
  'story-hard-work': gardeningSvg,
  'story-luck-hardwork': guardianAngelSvg,
  'story-champions': championsSvg,
  'story-recipe-success': recipeSuccessSvg,
  'story-nios': niosEducationSvg,
  'story-paper-bag': paperBagSvg,
  'story-tailoring': tailoringSvg,
  'story-kitchen': kitchenSvg
}
`

const code = `// Autogenerated with 100% complete unabridged content from docx archives and local asset mapping
${imageImports}

const rawArticles = ${JSON.stringify(cleaned, null, 2)}

export const allArticles = rawArticles.map((a) => ({
  ...a,
  heroImage: articleImagesMap[a.id] || null,
  imageUrl: a.imageUrl || articleImagesMap[a.id] || null
}))

export function getArticleById(id) {
  return allArticles.find((a) => a.id === id) || null
}
`

const allArticlesPath = path.join(__dirname, '../src/data/allArticles.js')
fs.writeFileSync(allArticlesPath, code, 'utf8')
console.log('Successfully updated allArticles.js and articles_complete.json')
